// Seed data mirroring filmkritiken-backend/infrastructure/db/seed/Seed.go
// Used only by the local dev stub API.

module.exports = [
  {
    poster: 'AQuietPlace.jpg',
    details: { beitragvon: 'Nico', besprochenam: '2026-08-15T12:00:00Z', bewertungoffen: true },
    film: {
      titel: 'A Quiet Place',
      altersfreigabe: 16,
      erscheinungsjahr: 2018,
      regie: 'John Krasinski',
      laenge: 90,
      originaltitel: '',
      originalsprache: 'Englisch, Amerikanische Zeichensprache',
      produktionsland: 'Vereinigte Staaten',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [],
  },
  {
    poster: 'KarateKid.jpg',
    details: { beitragvon: 'Stefan', besprochenam: '2026-07-17T12:00:00Z', bewertungoffen: false },
    film: {
      titel: 'Karate Kid',
      altersfreigabe: 12,
      erscheinungsjahr: 1984,
      regie: 'John G. Avildsen',
      laenge: 126,
      originaltitel: 'The Karate Kid',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigte Staaten',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [
      { von: 'Stefan', wertung: 9, enthaltung: false },
      { von: 'Nico', wertung: 8, enthaltung: false },
      { von: 'Dani', wertung: 9, enthaltung: false },
      { von: 'Tiffy', wertung: 7, enthaltung: false },
    ],
  },
  {
    poster: 'CitizenKane.jpg',
    details: { beitragvon: 'Dani', besprochenam: '2021-06-13T12:00:00Z', bewertungoffen: true },
    film: {
      titel: 'Citizen Kane',
      altersfreigabe: 12,
      erscheinungsjahr: 1941,
      regie: 'Orson Welles',
      laenge: 119,
      originaltitel: '',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigte Staaten',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [],
  },
  {
    poster: 'TropicThunder.jpg',
    details: { beitragvon: 'Flo', besprochenam: '2021-06-06T12:00:00Z', bewertungoffen: true },
    film: {
      titel: 'Tropic Thunder',
      altersfreigabe: 16,
      erscheinungsjahr: 2008,
      regie: 'Ben Stiller',
      laenge: 106,
      originaltitel: '',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigte Staaten, Vereinigtes Königreich, Deutschland',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [
      { von: 'Flo', wertung: 8, enthaltung: false },
      { von: 'Dani', wertung: 7, enthaltung: false },
    ],
  },
  {
    poster: 'MallCop.jpg',
    details: { beitragvon: 'Tiffy', besprochenam: '2021-06-19T12:00:00Z', bewertungoffen: true },
    film: {
      titel: 'Der Kaufhaus Cop',
      altersfreigabe: 6,
      erscheinungsjahr: 2009,
      regie: 'Steve Carr',
      laenge: 87,
      originaltitel: 'Paul Blart: Mall Cop',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigte Staaten',
      image: { source: '', copyright: 'Moviepilot', id: '' },
    },
    bewertungen: [],
  },
  {
    poster: 'SchindlersListe.jpg',
    details: { beitragvon: 'Flo', besprochenam: '2021-07-19T12:00:00Z', bewertungoffen: false },
    film: {
      titel: 'Schindlers Liste',
      altersfreigabe: 12,
      erscheinungsjahr: 1993,
      regie: 'Steven Spielberg',
      laenge: 195,
      originaltitel: '',
      originalsprache: 'Englisch, Deutsch, Polnisch, Hebräisch',
      produktionsland: 'Vereinigte Staaten',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [
      { von: 'Stefan', wertung: 10, enthaltung: false },
      { von: 'Flo', wertung: 9, enthaltung: false },
      { von: 'Nico', wertung: 10, enthaltung: false },
    ],
  },
  {
    poster: 'TaxiDriver.jpg',
    details: { beitragvon: 'Dani', besprochenam: '2021-07-24T12:00:00Z', bewertungoffen: false },
    film: {
      titel: 'Taxi Driver',
      altersfreigabe: 16,
      erscheinungsjahr: 1976,
      regie: 'Martin Scorsese',
      laenge: 114,
      originaltitel: '',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigte Staaten',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [
      { von: 'Dani', wertung: 9, enthaltung: false },
      { von: 'Stefan', wertung: 8, enthaltung: false },
    ],
  },
  {
    poster: 'GunsAkimbo.jpg',
    details: { beitragvon: 'Tiffy', besprochenam: '2021-08-15T12:00:00Z', bewertungoffen: false },
    film: {
      titel: 'Guns Akimbo',
      altersfreigabe: 16,
      erscheinungsjahr: 2019,
      regie: 'Jason Lei Howden',
      laenge: 97,
      originaltitel: '',
      originalsprache: 'Englisch',
      produktionsland: 'Neuseeland, Vereinigtes Königreich, Deutschland',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [{ von: 'Tiffy', wertung: 7, enthaltung: false }],
  },
  {
    poster: 'Alien.jpg',
    details: { beitragvon: 'Nico', besprochenam: '2021-08-21T12:00:00Z', bewertungoffen: false },
    film: {
      titel: 'Alien – Das unheimliche Wesen aus einer fremden Welt',
      altersfreigabe: 16,
      erscheinungsjahr: 1979,
      regie: 'Ridley Scott',
      laenge: 117,
      originaltitel: 'Alien',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigtes Königreich, Vereinigte Staaten',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [
      { von: 'Nico', wertung: 9, enthaltung: false },
      { von: 'Stefan', wertung: 9, enthaltung: false },
    ],
  },
  {
    poster: 'Zombiber.jpg',
    details: { beitragvon: 'Flo', besprochenam: '2021-09-19T12:00:00Z', bewertungoffen: true },
    film: {
      titel: 'Zombiber',
      altersfreigabe: 16,
      erscheinungsjahr: 2014,
      regie: 'Jordan Rubin',
      laenge: 77,
      originaltitel: 'Zombeavers',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigte Staaten',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [],
  },
  {
    poster: 'FistfulOfDollars.jpg',
    details: { beitragvon: 'Dani', besprochenam: '2021-10-02T12:00:00Z', bewertungoffen: true },
    film: {
      titel: 'Für eine Handvoll Dollar',
      altersfreigabe: 16,
      erscheinungsjahr: 1964,
      regie: 'Sergio Leone',
      laenge: 100,
      originaltitel: 'Per un pugno di dollari',
      originalsprache: 'Italienisch, Englisch, Spanisch',
      produktionsland: 'Italien, Spanien, Deutschland',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [],
  },
  {
    poster: 'PerAnhalter.jpg',
    details: { beitragvon: 'Tiffy', besprochenam: '2021-10-17T12:00:00Z', bewertungoffen: true },
    film: {
      titel: 'Per Anhalter durch die Galaxis',
      altersfreigabe: 6,
      erscheinungsjahr: 2005,
      regie: 'Garth Jennings',
      laenge: 110,
      originaltitel: 'The Hitchhiker’s Guide to the Galaxy',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigtes Königreich',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [],
  },
  {
    poster: 'AlienVsPredator2.jpg',
    details: { beitragvon: 'Nico', besprochenam: '2021-10-31T12:00:00Z', bewertungoffen: false },
    film: {
      titel: 'Alien vs. Predator 2',
      altersfreigabe: 18,
      erscheinungsjahr: 2007,
      regie: 'Colin Strause, Greg Strause',
      laenge: 90,
      originaltitel: 'Aliens vs. Predator: Requiem',
      originalsprache: 'Englisch',
      produktionsland: 'Vereinigte Staaten, Kanada',
      image: { source: '', copyright: 'IMDb', id: '' },
    },
    bewertungen: [
      { von: 'Nico', wertung: 4, enthaltung: false },
      { von: 'Stefan', wertung: 5, enthaltung: false },
    ],
  },
]
